// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/getting-started":{"path":"getting-started","id":"docs/getting-started","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/alert/index":{"id":"components/alert/index","path":"components/alert","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'F:/workspaces/01_fanyao/fanyao-ui/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'F:/workspaces/01_fanyao/fanyao-ui/.dumi/tmp-production/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'F:/workspaces/01_fanyao/fanyao-ui/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/getting-started': React.lazy(() => import(/* webpackChunkName: "docs__getting-started.md" */'F:/workspaces/01_fanyao/fanyao-ui/docs/getting-started.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'F:/workspaces/01_fanyao/fanyao-ui/docs/index.md')),
'components/alert/index': React.lazy(() => import(/* webpackChunkName: "alert__index.md" */'F:/workspaces/01_fanyao/fanyao-ui/src/alert/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'F:/workspaces/01_fanyao/fanyao-ui/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
