// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'F:/workspaces/01_fanyao/fanyao-ui/node_modules/dumi/theme-default/slots/SearchBar/index.js';
export * from 'F:/workspaces/01_fanyao/fanyao-ui/node_modules/dumi/theme-default/slots/SearchBar/index.js';
